app = "charamite"

primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[env]
  RAILS_ENV = "production"

[deploy]
  release_command = "bin/rails db:prepare"

[processes]
  app = "bundle exec rails s -b 0.0.0.0"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  processes = ["app"] 

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443