default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: charamite_development

test:
  <<: *default
  database: charamite_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
